title: Hung Vi Tourist
description: >-
  HÃ¹ng VÄ© Tourist â€“ Ä‘á»“ng hÃ nh cÃ¹ng báº¡n trÃªn má»i hÃ nh trÃ¬nh. 
  Dá»‹ch vá»¥ lÃ m VISA nhanh chÃ³ng, Ä‘áº·t vÃ© mÃ¡y bay giÃ¡ tá»‘t, tour du lá»‹ch Ä‘a dáº¡ng, uy tÃ­n vÃ  chuyÃªn nghiá»‡p.
site:
  url: /
  baseurl: /
navbar-links:
  PostNews: post-news
  VÃ© MÃ¡y Bay:
    - ğŸ›« VÃ© ná»™i Ä‘á»‹a: flights#domestic
    - ğŸŒ VÃ© quá»‘c táº¿: flights#international
    - ğŸ’º Äáº·t chá»— & hÃ nh lÃ½: flights#booking
  Tourist: 
    - ğŸï¸ Tour trong nÆ°á»›c: tours#domestic
    - ğŸ¯ Tour quá»‘c táº¿: tours#international
    - ğŸ¢ Combo du lá»‹ch: tours#combo
    - ğŸï¸ Du lá»‹ch tá»± tÃºc: tours#freeTravel
    - ğŸ–ï¸ Danh sÃ¡ch tour: tours/all-tours/
  Há»™ chiáº¿u VISA: 
    - ğŸ“‘ Visa du lá»‹ch: visa#travel
    - ğŸ’¼ Visa cÃ´ng tÃ¡c: visa#business
    - ğŸ“ Visa du há»c: visa#study
    - ğŸŒ Dá»‹ch vá»¥ khÃ¡c: visa#other
  HÃ¹ng VÄ© Service:
    - ğŸ“ LiÃªn há»‡: aboutme
    - ğŸ“ TÆ° váº¥n du lá»‹ch: service#consult
    - ğŸ¨ Äáº·t khÃ¡ch sáº¡n: service#hotel
    - ğŸš ThuÃª xe du lá»‹ch: service#carRental
    - ğŸ›³ï¸ Tour trá»n gÃ³i: service#packageTour
    - ğŸ‰ Tá»• chá»©c sá»± kiá»‡n: service#event
    - ğŸ¤ Há»£p tÃ¡c & Ä‘á»‘i tÃ¡c: service#partner
    - ğŸ›’ Dá»‹ch vá»¥ khÃ¡c: service#other

  # ğŸ—ï¸Tags: tags #thay tháº¿ báº±ng nÃºt tÃ¬m kiáº¿m.
avatar: "/img/Picture-HSL/logo-trans.png"
author:
  name: "\U0001F525HÃ¹ng VÄ© Tourist\U0001F525"
  rss: true
  email: hungvitourist@gmail.com
  facebook: hungvitourist
  instagram: "@hungvitourist"
  youtube: '@HÃ¹ngVÄ©Tourist'
  telephone: '0868 549 586'
  tiktok: '@hungvitourist'
company: "CÃ”NG TY TNHH Dá»ŠCH Vá»¤ DU Lá»ŠCH HÃ™NG VÄ¨"
company_SHORT_NAME: "âœ¨HÃ™NG VÄ¨ TOURISTâœ¨"
Tax-code: "MST: 0315546297"
address-1: "ğŸ“Œ: áº¤p BÃ¹ng Binh, XÃ£ HÆ°ng Thuáº­n, Tá»‰nh TÃ¢y Ninh"
address-2: "ğŸ“Œ: -----"
map-address-1: https://maps.app.goo.gl/
map-address-2: ------
footer-links-active:
  rss: false
  facebook: true
  email: true
  telephone: true
  youtube: true
  tiktok: true
  map-address-1: false
  map-address-2: false
share-links-active:
  facebook: true
  linkedin: true
#disqus: bang-nguyen-blog
google_analytics: G-97CTZX8FED
gtm: GTM-5WMQFC52
#fb_app_id: '721347795190980'
excerpt_length: 50
title-separator: '-'
timezone: Asia/Bangkok
markdown: kramdown
highlighter: rouge
permalink: '/:year-:month-:day-:title/'
paginate: 8
kramdown:
  input: GFM
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      sitemap: true
      comments: true
      social-share: true
  - scope:
      path: ''
    values:
      layout: page
      show-avatar: true
link-tags: true
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - LICENSE
  - README.md
  - Vagrantfile
collections:
  post-news:
    output: true
    permalink: /post-news/:name/   # Tin tá»©c, bÃ i viáº¿t
  flights:
    output: true
    permalink: /flights/:name/     # VÃ© mÃ¡y bay
  tours:
    output: true
    permalink: /tours/:name/       # Tour du lá»‹ch
  visa:
    output: true
    permalink: /visa/:name/        # Dá»‹ch vá»¥ Visa
  service:
    output: true
    permalink: /service/:name/     # CÃ¡c dá»‹ch vá»¥ bá»• trá»£ (khÃ¡ch sáº¡n, thuÃª xe, sá»± kiá»‡n...)

# Optionally, add permalink defaults (for better structure)
permalink: pretty

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-admin
  - jekyll-datapage-generator

page_gen:
  - data: 'tour_domestic'   # file _data/tour_domestic.csv
    template: 'tourlist'        # _layouts/tour.html
    name: 'ma_tour'         # tÃªn file sáº½ lÃ  giÃ¡ trá»‹ cá»™t ma_tour
    dir: 'tours/domestic'   # thÆ° má»¥c xuáº¥t file
  - data: 'tour_international'
    template: 'tourlist'
    name: 'ma_tour'
    dir: 'tours/international'
